name: adnipy-dev
channels:
  - defaults
dependencies:
  # required
  - python
  - pip

  # code checks
  - flake8
  - flake8-import-order
  - pep8-naming

  # code formatting
  - black

  # documentation
  - sphinx

  # testing
  - pytest
  - pytest-cov
  - coverage

  # requirements
  - pandas
  - matplotlib
  - jupyter

  # distribution
  - twine

  # pypi packages
  - pip:
    # code checks
    - flake8-bugbear
    - flake8-docstrings

    # documentation
    - sphinx-rtd-theme
    - watchdog
    - doc8

    # testing
    - tox
    - tox-conda

    # distribution
    - bumpversion
